#JDK kurulumunu yapıyoruz
#FROM adoptopenjdk/openjdk11
FROM openjdk:18
#Projemizin olduğu yeri gösteriyoruz ve kopyalıyoruz
ARG JAR_FILE=./target/votecounter-0.0.1-SNAPSHOT.jar
#ADD ${JAR_FILE} application.jar
COPY ./target/votecounter-0.0.1-SNAPSHOT.jar app.jar
#Çalışacağı portu belirliyoruz
EXPOSE 8080

#Projemizi calistıracak komutu yazıyoruz.
ENTRYPOINT ["java","-jar","/app.jar"]